version: "2"
services:
    web:
      build:
        context: .
      links:
        - mongo
      ports:
        - "5000:5000"
        - "3008:3008"
        - "1883:1883"
      environment:
        MQTT_WS_PORT: 3008
        MQTT_PORT: 1883
        HTTP_PORT: 5000
        MONGO_URI: mongodb://mongo:27017/test
    mongo:
      image: mongo
      ports:
        - "27027:27027"
